#!/bin/csh -f 

cd ..; /bin/mkdir ./obj; cd ./obj
gcc -m32 -g -Wall -I${DV_ROOT}/tools/pli -c ../get_plus_args.c
ar cr libniu_pli.a get_plus_args.o
mv libniu_pli.a ../linux
cd ../linux; /bin/rm -rf ../obj
