/*
* ========== Copyright Header Begin ==========================================
* 
* OpenSPARC T2 Processor File: tcu_trigout_reg.s
* Copyright (C) 1995-2007 Sun Microsystems, Inc. All Rights Reserved
* 4150 Network Circle, Santa Clara, California 95054, U.S.A.
*
* DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER. 
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; version 2 of the License.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*
* For the avoidance of doubt, and except that if any non-GPL license 
* choice is available it will apply instead, Sun elects to use only 
* the General Public License version 2 (GPLv2) at this time for any 
* software where a choice of GPL license versions is made 
* available with the language indicating that GPLv2 or any later version 
* may be used, or where a choice of which version of the GPL is applied is 
* otherwise unspecified. 
*
* Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa Clara, 
* CA 95054 USA or visit www.sun.com if you need additional information or 
* have any questions. 
*
* 
* ========== Copyright Header End ============================================
*/
#define MAIN_PAGE_NUCLEUS_ALSO
#define MAIN_PAGE_HV_ALSO

#include "hboot.s"
#include "asi_s.h"
#include "tcu_defines.h"

/************************************************************************
   Test case code start
 ************************************************************************/

.text
.global main

main:
	ta      T_CHANGE_HPRIV

	mov 0x3, %g7      ! loop counter or number of trigout generated by this diag
	
write_1_to_tcu_trigout_reg:
        setx    TCU_TRIGOUT_REG, %g1, %g2
	mov	1, %g3
        stx     %g3, [%g2]  ! write 1 to TCU's TRIGOUT reg which generates a trigout pulse
	membar #Sync

read_to_push_write:
	setx	TCU_CYCLE_COUNTER_REG, %g1, %g4
        ldx     [%g4], %g5
	membar #Sync
	
wait_after_read:
	setx 50, %g1, %g2
1:
	dec %g2
	brnz %g2, 1b
	nop

	dec %g7                               ! decrement loop counter
	brnz %g7, write_1_to_tcu_trigout_reg
	nop
	

/******************************************************
 * Exit code
 *******************************************************/
	
test_passed:
	EXIT_GOOD

test_failed:
	EXIT_BAD

/************************************************************************
   Test case data start
 ************************************************************************/
.data
user_data_start:
.end
