/*
* ========== Copyright Header Begin ==========================================
* 
* OpenSPARC T2 Processor File: dmu_pathto_defines.h
* Copyright (C) 1995-2007 Sun Microsystems, Inc. All Rights Reserved
* 4150 Network Circle, Santa Clara, California 95054, U.S.A.
*
* DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER. 
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; version 2 of the License.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*
* For the avoidance of doubt, and except that if any non-GPL license 
* choice is available it will apply instead, Sun elects to use only 
* the General Public License version 2 (GPLv2) at this time for any 
* software where a choice of GPL license versions is made 
* available with the language indicating that GPLv2 or any later version 
* may be used, or where a choice of which version of the GPL is applied is 
* otherwise unspecified. 
*
* Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa Clara, 
* CA 95054 USA or visit www.sun.com if you need additional information or 
* have any questions. 
*
* 
* ========== Copyright Header End ============================================
*/
`define FIRE_DLC_IMU_EQS_A_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_EQS_A_PATH.csr

`define FIRE_DLC_IMU_EQS_CSR_A_EQ_BASE_ADDRESS_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_EQS_A_PATH.csr.dmu_imu_eqs_default_grp.eq_base_address
`define FIRE_DLC_IMU_EQS_CSR_A_EQ_TAIL_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_EQS_A_PATH.csr.dmu_imu_eqs_default_grp.eq_tail
`define FIRE_DLC_IMU_EQS_CSR_A_EQ_HEAD_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_EQS_A_PATH.csr.dmu_imu_eqs_default_grp.eq_head

//----- Variable definitions for instance dmu_imu_iss_a

`define FIRE_DLC_IMU_ISS_A_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr

`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_20_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_20
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_21_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_21
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_22_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_22
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_23_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_23
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_24_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_24
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_25_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_25
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_26_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_26
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_27_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_27
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_28_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_28
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_29_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_29
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_30_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_30
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_31_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_31
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_32_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_32
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_33_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_33
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_34_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_34
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_35_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_35
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_36_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_36
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_37_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_37
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_38_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_38
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_39_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_39
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_40_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_40
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_41_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_41
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_42_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_42
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_43_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_43
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_44_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_44
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_45_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_45
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_46_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_46
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_47_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_47
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_48_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_48
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_49_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_49
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_50_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_50
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_51_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_51
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_52_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_52
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_53_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_53
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_54_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_54
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_55_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_55
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_56_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_56
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_57_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_57
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_58_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_58
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_59_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_59
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_62_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_62
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_MAPPING_63_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_63
`define FIRE_DLC_IMU_ISS_CSR_A_INTERRUPT_RETRY_TIMER_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_A_PATH.csr.dmu_imu_iss_default_grp.interrupt_retry_timer

//----- Variable definitions for instance dmu_imu_rds_intx_a

`define FIRE_DLC_IMU_RDS_INTX_A_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_RDS_INTX_A_PATH.csr

`define FIRE_DLC_IMU_RDS_INTX_CSR_A_INT_A_INT_CLR_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_RDS_INTX_A_PATH.csr.dmu_imu_rds_intx_default_grp.int_a_int_clr_reg
`define FIRE_DLC_IMU_RDS_INTX_CSR_A_INT_B_INT_CLR_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_RDS_INTX_A_PATH.csr.dmu_imu_rds_intx_default_grp.int_b_int_clr_reg
`define FIRE_DLC_IMU_RDS_INTX_CSR_A_INT_C_INT_CLR_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_RDS_INTX_A_PATH.csr.dmu_imu_rds_intx_default_grp.int_c_int_clr_reg
`define FIRE_DLC_IMU_RDS_INTX_CSR_A_INT_D_INT_CLR_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_RDS_INTX_A_PATH.csr.dmu_imu_rds_intx_default_grp.int_d_int_clr_reg

//----- Variable definitions for instance dmu_imu_rds_msi_a

`define FIRE_DLC_IMU_RDS_MSI_A_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_RDS_MSI_A_PATH.csr

`define FIRE_DLC_IMU_RDS_MSI_CSR_A_INT_MONDO_DATA_0_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_RDS_MSI_A_PATH.csr.dmu_imu_rds_msi_default_grp.int_mondo_data_0_reg
`define FIRE_DLC_IMU_RDS_MSI_CSR_A_INT_MONDO_DATA_1_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_RDS_MSI_A_PATH.csr.dmu_imu_rds_msi_default_grp.int_mondo_data_1_reg

//----- Variable definitions for instance dmu_imu_rds_mess_a

`define FIRE_DLC_IMU_RDS_MESS_A_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_RDS_MESS_A_PATH.csr

`define FIRE_DLC_IMU_RDS_MESS_CSR_A_ERR_COR_MAPPING_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_RDS_MESS_A_PATH.csr.dmu_imu_rds_mess_default_grp.err_cor_mapping
`define FIRE_DLC_IMU_RDS_MESS_CSR_A_ERR_NONFATAL_MAPPING_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_RDS_MESS_A_PATH.csr.dmu_imu_rds_mess_default_grp.err_nonfatal_mapping
`define FIRE_DLC_IMU_RDS_MESS_CSR_A_ERR_FATAL_MAPPING_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_RDS_MESS_A_PATH.csr.dmu_imu_rds_mess_default_grp.err_fatal_mapping
`define FIRE_DLC_IMU_RDS_MESS_CSR_A_PM_PME_MAPPING_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_RDS_MESS_A_PATH.csr.dmu_imu_rds_mess_default_grp.pm_pme_mapping
`define FIRE_DLC_IMU_RDS_MESS_CSR_A_PME_TO_ACK_MAPPING_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_RDS_MESS_A_PATH.csr.dmu_imu_rds_mess_default_grp.pme_to_ack_mapping

//----- Variable definitions for instance dmu_imu_ics_a

`define FIRE_DLC_IMU_ICS_A_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ICS_A_PATH.csr

`define FIRE_DLC_IMU_ICS_CSR_A_IMU_ERROR_LOG_EN_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ICS_A_PATH.csr.dmu_imu_ics_default_grp.imu_error_log_en_reg
`define FIRE_DLC_IMU_ICS_CSR_A_IMU_INT_EN_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ICS_A_PATH.csr.dmu_imu_ics_default_grp.imu_int_en_reg
`define FIRE_DLC_IMU_ICS_CSR_A_IMU_LOGGED_ERROR_STATUS_REG_RW1C_ALIAS_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ICS_A_PATH.csr.dmu_imu_ics_default_grp.imu_logged_error_status_reg
`define FIRE_DLC_IMU_ICS_CSR_A_IMU_LOGGED_ERROR_STATUS_REG_RW1S_ALIAS_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ICS_A_PATH.csr.dmu_imu_ics_default_grp.imu_logged_error_status_reg
`define FIRE_DLC_IMU_ICS_CSR_A_IMU_RDS_ERROR_LOG_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ICS_A_PATH.csr.dmu_imu_ics_default_grp.imu_rds_error_log_reg
`define FIRE_DLC_IMU_ICS_CSR_A_IMU_SCS_ERROR_LOG_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ICS_A_PATH.csr.dmu_imu_ics_default_grp.imu_scs_error_log_reg
`define FIRE_DLC_IMU_ICS_CSR_A_IMU_EQS_ERROR_LOG_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ICS_A_PATH.csr.dmu_imu_ics_default_grp.imu_eqs_error_log_reg
`define FIRE_DLC_IMU_ICS_CSR_A_DMC_INTERRUPT_MASK_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ICS_A_PATH.csr.dmu_imu_ics_default_grp.dmc_interrupt_mask_reg
`define FIRE_DLC_IMU_ICS_CSR_A_IMU_PERF_CNTRL_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ICS_A_PATH.csr.dmu_imu_ics_default_grp.imu_perf_cntrl
`define FIRE_DLC_IMU_ICS_CSR_A_IMU_PERF_CNT0_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ICS_A_PATH.csr.dmu_imu_ics_default_grp.imu_perf_cnt0
`define FIRE_DLC_IMU_ICS_CSR_A_IMU_PERF_CNT1_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ICS_A_PATH.csr.dmu_imu_ics_default_grp.imu_perf_cnt1
`define FIRE_DLC_IMU_ICS_CSR_A_MSI_32_ADDR_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ICS_A_PATH.csr.dmu_imu_ics_default_grp.msi_32_addr_reg
`define FIRE_DLC_IMU_ICS_CSR_A_MSI_64_ADDR_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ICS_A_PATH.csr.dmu_imu_ics_default_grp.msi_64_addr_reg
`define FIRE_DLC_IMU_ICS_CSR_A_MEM_64_PCIE_OFFSET_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ICS_A_PATH.csr.dmu_imu_ics_default_grp.mem_64_pcie_offset_reg

//----- Variable definitions for instance dmu_mmu_csr_a

`define FIRE_DLC_MMU_CSR_A_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_MMU_CSR_A_PATH.csr

`define FIRE_DLC_MMU_CSR_A_CTL_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_MMU_CSR_A_PATH.csr.dmu_mmu_csr_default_grp.ctl
`define FIRE_DLC_MMU_CSR_A_TSB_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_MMU_CSR_A_PATH.csr.dmu_mmu_csr_default_grp.tsb
`define FIRE_DLC_MMU_CSR_A_FSH_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_MMU_CSR_A_PATH.csr.dmu_mmu_csr_default_grp.fsh
`define FIRE_DLC_MMU_CSR_A_LOG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_MMU_CSR_A_PATH.csr.dmu_mmu_csr_default_grp.log
`define FIRE_DLC_MMU_CSR_A_INT_EN_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_MMU_CSR_A_PATH.csr.dmu_mmu_csr_default_grp.int_en
`define FIRE_DLC_MMU_CSR_A_ERR_RW1C_ALIAS_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_MMU_CSR_A_PATH.csr.dmu_mmu_csr_default_grp.err
`define FIRE_DLC_MMU_CSR_A_ERR_RW1S_ALIAS_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_MMU_CSR_A_PATH.csr.dmu_mmu_csr_default_grp.err
`define FIRE_DLC_MMU_CSR_A_FLTA_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_MMU_CSR_A_PATH.csr.dmu_mmu_csr_default_grp.flta
`define FIRE_DLC_MMU_CSR_A_FLTS_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_MMU_CSR_A_PATH.csr.dmu_mmu_csr_default_grp.flts
`define FIRE_DLC_MMU_CSR_A_PRFC_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_MMU_CSR_A_PATH.csr.dmu_mmu_csr_default_grp.prfc
`define FIRE_DLC_MMU_CSR_A_PRF0_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_MMU_CSR_A_PATH.csr.dmu_mmu_csr_default_grp.prf0
`define FIRE_DLC_MMU_CSR_A_PRF1_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_MMU_CSR_A_PATH.csr.dmu_mmu_csr_default_grp.prf1

//----- Variable definitions for instance dmu_ilu_cib_a

`define FIRE_DLC_ILU_CIB_A_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_ILU_CIB_A_PATH.csr

`define FIRE_DLC_ILU_CIB_CSR_A_ILU_LOG_EN_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_ILU_CIB_A_PATH.csr.dmu_ilu_cib_default_grp.ilu_log_en
`define FIRE_DLC_ILU_CIB_CSR_A_ILU_INT_EN_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_ILU_CIB_A_PATH.csr.dmu_ilu_cib_default_grp.ilu_int_en
`define FIRE_DLC_ILU_CIB_CSR_A_ILU_LOG_ERR_RW1C_ALIAS_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_ILU_CIB_A_PATH.csr.dmu_ilu_cib_default_grp.ilu_log_err
`define FIRE_DLC_ILU_CIB_CSR_A_ILU_LOG_ERR_RW1S_ALIAS_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_ILU_CIB_A_PATH.csr.dmu_ilu_cib_default_grp.ilu_log_err
`define FIRE_DLC_ILU_CIB_CSR_A_PEC_INT_EN_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_ILU_CIB_A_PATH.csr.dmu_ilu_cib_default_grp.pec_int_en

//----- Variable definitions for instance dmu_cru_a

`define FIRE_DLC_CRU_A_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_CRU_A_PATH.csr

`define FIRE_DLC_CRU_CSR_A_DMC_DBG_SEL_A_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_CRU_A_PATH.csr.dmu_cru_default_grp.dmc_dbg_sel_a_reg
`define FIRE_DLC_CRU_CSR_A_DMC_DBG_SEL_B_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_CRU_A_PATH.csr.dmu_cru_default_grp.dmc_dbg_sel_b_reg
`define FIRE_DLC_CRU_CSR_A_DMC_PCIE_CFG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_CRU_A_PATH.csr.dmu_cru_default_grp.dmc_pcie_cfg

//----- Variable definitions for instance fire_dlc_psb_a

`define FIRE_DLC_PSB_A_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_PSB_A_PATH.csr


//----- Variable definitions for instance fire_dlc_tsb_a

`define FIRE_DLC_TSB_A_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_TSB_A_PATH.csr
`define FIRE_DLC_TSB_CSR_A_TSB_STS_PATH_TO    `FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_TSB_A_PATH.csr.tsb_sts



//----- Variable definitions for instance ptl_ctb_tlr_a changed to 
//----- Variable definitions for instance ptl_ctb_tlr_a

`define FIRE_PLC_TLU_CTB_TLR_A_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr

`define FIRE_PLC_TLU_CTB_TLR_CSR_A_TLU_CTL_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.tlu_ctl
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_TRN_OFF_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.trn_off
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_TLU_ICI_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.tlu_ici
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_TLU_DIAG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.tlu_diag
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_OE_LOG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.oe_log
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_OE_INT_EN_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.oe_int_en
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_OE_ERR_RW1C_ALIAS_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.oe_err
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_OE_ERR_RW1S_ALIAS_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.oe_err
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_ROE_HDR1_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.roe_hdr1
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_ROE_HDR2_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.roe_hdr2
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_TOE_HDR1_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.toe_hdr1
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_TOE_HDR2_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.toe_hdr2
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_TLU_PRFC_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.tlu_prfc
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_TLU_PRF0_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.tlu_prf0
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_TLU_PRF1_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.tlu_prf1
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_TLU_PRF2_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.tlu_prf2
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_TLU_DBG_SEL_A_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.tlu_dbg_sel_a
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_TLU_DBG_SEL_B_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.tlu_dbg_sel_b
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_DEV_CAP_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.dev_cap
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_DEV_CTL_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.dev_ctl
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_DEV_STS_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.dev_sts
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_LNK_CAP_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.lnk_cap
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_LNK_CTL_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.lnk_ctl
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_SLT_CAP_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.slt_cap
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_UE_LOG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.ue_log
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_UE_INT_EN_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.ue_int_en
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_UE_ERR_RW1C_ALIAS_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.ue_err
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_UE_ERR_RW1S_ALIAS_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.ue_err
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_RUE_HDR1_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.rue_hdr1
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_RUE_HDR2_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.rue_hdr2
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_TUE_HDR1_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.tue_hdr1
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_TUE_HDR2_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.tue_hdr2
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_CE_LOG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.ce_log
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_CE_INT_EN_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.ce_int_en
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_CE_ERR_RW1C_ALIAS_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.ce_err
`define FIRE_PLC_TLU_CTB_TLR_CSR_A_CE_ERR_RW1S_ALIAS_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_A_PATH.csr.ptl_ctb_tlr_default_grp.ce_err

//----- Variable definitions for instance ptl_ctb_lpr_a

`define FIRE_PLC_TLU_CTB_LPR_A_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_LPR_A_PATH.csr


//----- Variable definitions for instance dmu_imu_eqs_b

`define FIRE_DLC_IMU_EQS_B_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_EQS_B_PATH.csr

`define FIRE_DLC_IMU_EQS_CSR_B_EQ_BASE_ADDRESS_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_EQS_B_PATH.csr.dmu_imu_eqs_default_grp.eq_base_address
`define FIRE_DLC_IMU_EQS_CSR_B_EQ_TAIL_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_EQS_B_PATH.csr.dmu_imu_eqs_default_grp.eq_tail
`define FIRE_DLC_IMU_EQS_CSR_B_EQ_HEAD_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_EQS_B_PATH.csr.dmu_imu_eqs_default_grp.eq_head

//----- Variable definitions for instance dmu_imu_iss_b

`define FIRE_DLC_IMU_ISS_B_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr

`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_20_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_20
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_21_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_21
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_22_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_22
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_23_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_23
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_24_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_24
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_25_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_25
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_26_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_26
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_27_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_27
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_28_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_28
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_29_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_29
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_30_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_30
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_31_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_31
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_32_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_32
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_33_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_33
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_34_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_34
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_35_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_35
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_36_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_36
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_37_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_37
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_38_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_38
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_39_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_39
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_40_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_40
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_41_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_41
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_42_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_42
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_43_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_43
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_44_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_44
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_45_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_45
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_46_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_46
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_47_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_47
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_48_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_48
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_49_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_49
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_50_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_50
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_51_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_51
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_52_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_52
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_53_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_53
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_54_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_54
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_55_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_55
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_56_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_56
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_57_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_57
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_58_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_58
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_59_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_59
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_62_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_62
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_MAPPING_63_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_mapping_63
`define FIRE_DLC_IMU_ISS_CSR_B_INTERRUPT_RETRY_TIMER_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ISS_B_PATH.csr.dmu_imu_iss_default_grp.interrupt_retry_timer

//----- Variable definitions for instance dmu_imu_rds_intx_b

`define FIRE_DLC_IMU_RDS_INTX_B_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_RDS_INTX_B_PATH.csr

`define FIRE_DLC_IMU_RDS_INTX_CSR_B_INT_A_INT_CLR_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_RDS_INTX_B_PATH.csr.dmu_imu_rds_intx_default_grp.int_a_int_clr_reg
`define FIRE_DLC_IMU_RDS_INTX_CSR_B_INT_B_INT_CLR_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_RDS_INTX_B_PATH.csr.dmu_imu_rds_intx_default_grp.int_b_int_clr_reg
`define FIRE_DLC_IMU_RDS_INTX_CSR_B_INT_C_INT_CLR_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_RDS_INTX_B_PATH.csr.dmu_imu_rds_intx_default_grp.int_c_int_clr_reg
`define FIRE_DLC_IMU_RDS_INTX_CSR_B_INT_D_INT_CLR_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_RDS_INTX_B_PATH.csr.dmu_imu_rds_intx_default_grp.int_d_int_clr_reg

//----- Variable definitions for instance dmu_imu_rds_msi_b

`define FIRE_DLC_IMU_RDS_MSI_B_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_RDS_MSI_B_PATH.csr

`define FIRE_DLC_IMU_RDS_MSI_CSR_B_INT_MONDO_DATA_0_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_RDS_MSI_B_PATH.csr.dmu_imu_rds_msi_default_grp.int_mondo_data_0_reg
`define FIRE_DLC_IMU_RDS_MSI_CSR_B_INT_MONDO_DATA_1_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_RDS_MSI_B_PATH.csr.dmu_imu_rds_msi_default_grp.int_mondo_data_1_reg

//----- Variable definitions for instance dmu_imu_rds_mess_b

`define FIRE_DLC_IMU_RDS_MESS_B_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_RDS_MESS_B_PATH.csr

`define FIRE_DLC_IMU_RDS_MESS_CSR_B_ERR_COR_MAPPING_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_RDS_MESS_B_PATH.csr.dmu_imu_rds_mess_default_grp.err_cor_mapping
`define FIRE_DLC_IMU_RDS_MESS_CSR_B_ERR_NONFATAL_MAPPING_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_RDS_MESS_B_PATH.csr.dmu_imu_rds_mess_default_grp.err_nonfatal_mapping
`define FIRE_DLC_IMU_RDS_MESS_CSR_B_ERR_FATAL_MAPPING_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_RDS_MESS_B_PATH.csr.dmu_imu_rds_mess_default_grp.err_fatal_mapping
`define FIRE_DLC_IMU_RDS_MESS_CSR_B_PM_PME_MAPPING_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_RDS_MESS_B_PATH.csr.dmu_imu_rds_mess_default_grp.pm_pme_mapping
`define FIRE_DLC_IMU_RDS_MESS_CSR_B_PME_TO_ACK_MAPPING_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_RDS_MESS_B_PATH.csr.dmu_imu_rds_mess_default_grp.pme_to_ack_mapping

//----- Variable definitions for instance dmu_imu_ics_b

`define FIRE_DLC_IMU_ICS_B_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ICS_B_PATH.csr

`define FIRE_DLC_IMU_ICS_CSR_B_IMU_ERROR_LOG_EN_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ICS_B_PATH.csr.dmu_imu_ics_default_grp.imu_error_log_en_reg
`define FIRE_DLC_IMU_ICS_CSR_B_IMU_INT_EN_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ICS_B_PATH.csr.dmu_imu_ics_default_grp.imu_int_en_reg
`define FIRE_DLC_IMU_ICS_CSR_B_IMU_LOGGED_ERROR_STATUS_REG_RW1C_ALIAS_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ICS_B_PATH.csr.dmu_imu_ics_default_grp.imu_logged_error_status_reg
`define FIRE_DLC_IMU_ICS_CSR_B_IMU_LOGGED_ERROR_STATUS_REG_RW1S_ALIAS_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ICS_B_PATH.csr.dmu_imu_ics_default_grp.imu_logged_error_status_reg
`define FIRE_DLC_IMU_ICS_CSR_B_IMU_RDS_ERROR_LOG_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ICS_B_PATH.csr.dmu_imu_ics_default_grp.imu_rds_error_log_reg
`define FIRE_DLC_IMU_ICS_CSR_B_IMU_SCS_ERROR_LOG_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ICS_B_PATH.csr.dmu_imu_ics_default_grp.imu_scs_error_log_reg
`define FIRE_DLC_IMU_ICS_CSR_B_IMU_EQS_ERROR_LOG_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ICS_B_PATH.csr.dmu_imu_ics_default_grp.imu_eqs_error_log_reg
`define FIRE_DLC_IMU_ICS_CSR_B_DMC_INTERRUPT_MASK_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ICS_B_PATH.csr.dmu_imu_ics_default_grp.dmc_interrupt_mask_reg
`define FIRE_DLC_IMU_ICS_CSR_B_IMU_PERF_CNTRL_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ICS_B_PATH.csr.dmu_imu_ics_default_grp.imu_perf_cntrl
`define FIRE_DLC_IMU_ICS_CSR_B_IMU_PERF_CNT0_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ICS_B_PATH.csr.dmu_imu_ics_default_grp.imu_perf_cnt0
`define FIRE_DLC_IMU_ICS_CSR_B_IMU_PERF_CNT1_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ICS_B_PATH.csr.dmu_imu_ics_default_grp.imu_perf_cnt1
`define FIRE_DLC_IMU_ICS_CSR_B_MSI_32_ADDR_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ICS_B_PATH.csr.dmu_imu_ics_default_grp.msi_32_addr_reg
`define FIRE_DLC_IMU_ICS_CSR_B_MSI_64_ADDR_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ICS_B_PATH.csr.dmu_imu_ics_default_grp.msi_64_addr_reg
`define FIRE_DLC_IMU_ICS_CSR_B_MEM_64_PCIE_OFFSET_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_IMU_ICS_B_PATH.csr.dmu_imu_ics_default_grp.mem_64_pcie_offset_reg

//----- Variable definitions for instance dmu_mmu_csr_b

`define FIRE_DLC_MMU_CSR_B_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_MMU_CSR_B_PATH.csr

`define FIRE_DLC_MMU_CSR_B_CTL_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_MMU_CSR_B_PATH.csr.dmu_mmu_csr_default_grp.ctl
`define FIRE_DLC_MMU_CSR_B_TSB_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_MMU_CSR_B_PATH.csr.dmu_mmu_csr_default_grp.tsb
`define FIRE_DLC_MMU_CSR_B_FSH_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_MMU_CSR_B_PATH.csr.dmu_mmu_csr_default_grp.fsh
`define FIRE_DLC_MMU_CSR_B_LOG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_MMU_CSR_B_PATH.csr.dmu_mmu_csr_default_grp.log
`define FIRE_DLC_MMU_CSR_B_INT_EN_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_MMU_CSR_B_PATH.csr.dmu_mmu_csr_default_grp.int_en
`define FIRE_DLC_MMU_CSR_B_ERR_RW1C_ALIAS_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_MMU_CSR_B_PATH.csr.dmu_mmu_csr_default_grp.err
`define FIRE_DLC_MMU_CSR_B_ERR_RW1S_ALIAS_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_MMU_CSR_B_PATH.csr.dmu_mmu_csr_default_grp.err
`define FIRE_DLC_MMU_CSR_B_FLTA_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_MMU_CSR_B_PATH.csr.dmu_mmu_csr_default_grp.flta
`define FIRE_DLC_MMU_CSR_B_FLTS_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_MMU_CSR_B_PATH.csr.dmu_mmu_csr_default_grp.flts
`define FIRE_DLC_MMU_CSR_B_PRFC_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_MMU_CSR_B_PATH.csr.dmu_mmu_csr_default_grp.prfc
`define FIRE_DLC_MMU_CSR_B_PRF0_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_MMU_CSR_B_PATH.csr.dmu_mmu_csr_default_grp.prf0
`define FIRE_DLC_MMU_CSR_B_PRF1_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_MMU_CSR_B_PATH.csr.dmu_mmu_csr_default_grp.prf1

//----- Variable definitions for instance dmu_ilu_cib_b

`define FIRE_DLC_ILU_CIB_B_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_ILU_CIB_B_PATH.csr

`define FIRE_DLC_ILU_CIB_CSR_B_ILU_LOG_EN_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_ILU_CIB_B_PATH.csr.dmu_ilu_cib_default_grp.ilu_log_en
`define FIRE_DLC_ILU_CIB_CSR_B_ILU_INT_EN_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_ILU_CIB_B_PATH.csr.dmu_ilu_cib_default_grp.ilu_int_en
`define FIRE_DLC_ILU_CIB_CSR_B_ILU_LOG_ERR_RW1C_ALIAS_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_ILU_CIB_B_PATH.csr.dmu_ilu_cib_default_grp.ilu_log_err
`define FIRE_DLC_ILU_CIB_CSR_B_ILU_LOG_ERR_RW1S_ALIAS_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_ILU_CIB_B_PATH.csr.dmu_ilu_cib_default_grp.ilu_log_err
`define FIRE_DLC_ILU_CIB_CSR_B_PEC_INT_EN_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_ILU_CIB_B_PATH.csr.dmu_ilu_cib_default_grp.pec_int_en

//----- Variable definitions for instance dmu_cru_b

`define FIRE_DLC_CRU_B_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_CRU_B_PATH.csr

`define FIRE_DLC_CRU_CSR_B_DMC_DBG_SEL_A_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_CRU_B_PATH.csr.dmu_cru_default_grp.dmc_dbg_sel_a_reg
`define FIRE_DLC_CRU_CSR_B_DMC_DBG_SEL_B_REG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_CRU_B_PATH.csr.dmu_cru_default_grp.dmc_dbg_sel_b_reg
`define FIRE_DLC_CRU_CSR_B_DMC_PCIE_CFG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_CRU_B_PATH.csr.dmu_cru_default_grp.dmc_pcie_cfg

//----- Variable definitions for instance fire_dlc_psb_b

`define FIRE_DLC_PSB_B_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_PSB_B_PATH.csr


//----- Variable definitions for instance fire_dlc_tsb_b

`define FIRE_DLC_TSB_B_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_TSB_B_PATH.csr
`define FIRE_DLC_TSB_CSR_B_TSB_STS_PATH_TO    `FIRE_TB_PATH`FIRE_PATH`FIRE_DLC_TSB_B_PATH.csr.tsb_sts


//----- Variable definitions for instance ptl_ctb_tlr_b

`define FIRE_PLC_TLU_CTB_TLR_B_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr

`define FIRE_PLC_TLU_CTB_TLR_CSR_B_TLU_CTL_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.tlu_ctl
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_TRN_OFF_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.trn_off
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_TLU_ICI_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.tlu_ici
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_TLU_DIAG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.tlu_diag
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_OE_LOG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.oe_log
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_OE_INT_EN_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.oe_int_en
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_OE_ERR_RW1C_ALIAS_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.oe_err
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_OE_ERR_RW1S_ALIAS_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.oe_err
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_ROE_HDR1_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.roe_hdr1
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_ROE_HDR2_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.roe_hdr2
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_TOE_HDR1_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.toe_hdr1
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_TOE_HDR2_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.toe_hdr2
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_TLU_PRFC_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.tlu_prfc
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_TLU_PRF0_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.tlu_prf0
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_TLU_PRF1_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.tlu_prf1
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_TLU_PRF2_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.tlu_prf2
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_TLU_DBG_SEL_A_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.tlu_dbg_sel_a
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_TLU_DBG_SEL_B_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.tlu_dbg_sel_b
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_DEV_CAP_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.dev_cap
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_DEV_CTL_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.dev_ctl
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_DEV_STS_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.dev_sts
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_LNK_CAP_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.lnk_cap
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_LNK_CTL_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.lnk_ctl
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_SLT_CAP_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.slt_cap
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_UE_LOG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.ue_log
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_UE_INT_EN_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.ue_int_en
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_UE_ERR_RW1C_ALIAS_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.ue_err
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_UE_ERR_RW1S_ALIAS_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.ue_err
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_RUE_HDR1_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.rue_hdr1
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_RUE_HDR2_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.rue_hdr2
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_TUE_HDR1_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.tue_hdr1
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_TUE_HDR2_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.tue_hdr2
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_CE_LOG_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.ce_log
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_CE_INT_EN_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.ce_int_en
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_CE_ERR_RW1C_ALIAS_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.ce_err
`define FIRE_PLC_TLU_CTB_TLR_CSR_B_CE_ERR_RW1S_ALIAS_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_TLR_B_PATH.csr.ptl_ctb_tlr_default_grp.ce_err

//----- Variable definitions for instance ptl_ctb_lpr_b

`define FIRE_PLC_TLU_CTB_LPR_B_PATH_TO	`FIRE_TB_PATH`FIRE_PATH`FIRE_PLC_TLU_CTB_LPR_B_PATH.csr

