################################################################################
##
## File:	<unit>/Makefile
## Description:
## -----------
##	Makefile for unit's coverage objects, called by Makefile in
##	testbench vera directory.
## NOTE:
## ----
##	This file just sets some unit specific variables and then
##	includes the common ../CovMakefile.inc.
## Caution:
## -------
##	Only works with "gmake".
##
## $Id: Makefile,v 1.1 2005/10/14 01:07:06 cb150247 Exp $
##
################################################################################

################################################################################
# variable declarations
################################################################################

## To over-ride default setting.
## UNIT		:=

## Explicit list of coverage objects
COV_OBJS	:=

include ../CovMakefile.inc
