#!/bin/csh -f -v

setenv CDS_INST_DIR $NCV_HOME
setenv INSTALL_DIR $NCV_HOME
setenv ARCH sun4v

setenv LD_LIBRARY_PATH "$NCV_HOME/tools/lib:$NCV_HOME/tools/verilog/lib"

compile.0
make -f Makefile.nc
